py_binary(
    name = "build_pip_package",
    srcs = [
        "build_pip_package.py",
    ],
    data = [
        "setup.py",
        "requirements.txt",
        "//aistreams/python/apps:aisctl",
    ],
)
