# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Dockerfile for the development image of aistreams-sdk.
#
# To build:
# docker build -f Dockerfile.dev . -t <image_tag>

FROM ubuntu:18.04

# Install gstreamer.
RUN apt-get update && apt-get install -y --no-install-recommends \
         libgstreamer1.0-0 \
         libgstreamer-plugins-base1.0-dev \
         gstreamer1.0-dev \
         gstreamer1.0-plugins-base \
         gstreamer1.0-plugins-base-apps \
         gstreamer1.0-plugins-good \
         gstreamer1.0-plugins-bad \
         gstreamer1.0-plugins-ugly \
         gstreamer1.0-libav \
         gstreamer1.0-rtsp \
         libgstrtspserver-1.0-dev \
         && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install bazel.
RUN apt-get update && apt-get install -y --no-install-recommends \
         ca-certificates \
         curl \
         gnupg \
         && \
    curl -fsSL https://bazel.build/bazel-release.pub.gpg | \
       gpg --dearmor > /etc/apt/trusted.gpg.d/bazel.gpg && \
    echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | \
      tee /etc/apt/sources.list.d/bazel.list && \
    apt-get update && apt-get install -y --no-install-recommends bazel && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Install python.
RUN apt-get update && apt-get install -y --no-install-recommends \
         python3 \
         python3-pip && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip --no-cache-dir install --upgrade \
         pip \
         setuptools \
         wheel

RUN ln -s $(which python3) /usr/local/bin/python

RUN apt-get update && apt-get install -y --no-install-recommends \
         python3-dev \
         python3-venv \
         && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Install development tools.
RUN apt-get update && apt-get install -y --no-install-recommends \
         build-essential \
         git \
         vim \
         wget \
         && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
