package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "mock_stream_service",
    testonly = 1,
    srcs = [],
    hdrs = [
        "mock_stream_service.h",
    ],
    deps = [
        "//aistreams/port:grpc++",
        "//aistreams/port:gtest_main",
        "//aistreams/proto:stream_cc_grpc",
    ],
)
