package(
    default_visibility = ["//aistreams:__subpackages__"],
)

filegroup(
    name = "exported_testdata",
    srcs = glob([
        "jpegs/*.jpg",
        "ppms/*.ppm",
        "pngs/*.png",
    ]),
)
